### ISSUE TITLE
Create MVP

### ISSUE THREAD

**Issue by saifahn** [saifahn/cardnames#1]
## Summary

It's best to start small, with something you can actually get out there for people to play. What's the point otherwise?

## Tasks

- [x] Initial state - no game in progress
  - #2 
- [x] Create a new game
  - [x] Get cards, randomize
- [x] Game interaction
  - [x] Game interaction: enter clues
  - [x] Game interaction: guess a card
  - [x] Game interaction: pass turn
- [x] Add a basic UI for the board
  - [x] #3
  - [x] #5
- [x] Host it somewhere

We don't even need to assign players to teams at the moment. Just display somewhere obvious what stage of the game it is.

## Future enhancements

- [ ] Teams
- [ ] Spymaster assigned to one person
- [ ] Rejoining
- [ ] Rooms

**Comment by saifahn** [comment]
## 2024-12-02

I'm going to rewrite the MVP - most of this stuff isn't even necessary for an MVP!
