### ISSUE TITLE
Add "operative" view

### ISSUE THREAD

**Issue by saifahn** [saifahn/cardnames#3]
## Overview

![cmr-119-dhund-operative](https://github.com/user-attachments/assets/1d60b598-0291-4d54-aae0-d77e7feb6bd7)

This tracks the tasks required for the non-spymaster player UI.

## Tasks

- [x] Show board of cards
- [x] Allow guessing of cards (will require updates in the backend as well)
- [x] Show state of cards
- [x] Show clue given by Spymaster
- [x] Show clear status of whose turn it is etc.
